### ISSUE TITLE
Integrated JBPM interface - No process diagram available

### ISSUE THREAD

**Issue by vagstef** [eclipse-opensmartclide/smartclide-ide-front-end#51]
Process diagram is missing

![jbpm_diagram](https://user-images.githubusercontent.com/877582/209941670-c5029dfb-a104-43de-b03c-c193b67272fa.png)

**Comment by deanone** [comment]
@vagstef in order to create a new Business Process you need to first create a new asset (by clicking the "Add Asset" button) at the main view of your project in the business central (see attached image).

![screenshot_opensmartclide_1](https://user-images.githubusercontent.com/5978626/211570789-02b6506b-e386-443c-a632-4a2e4c262842.png)

Then, since you created an asset of type "Business Process" the business process editor opens (see attached image).

![screenshot_opensmartclide_2](https://user-images.githubusercontent.com/5978626/211571243-9c275bc9-0486-4aaa-a37d-9004c4b03136.png)
